### ISSUE TITLE
Crashing if you have multiple connections opened in the same time

### ISSUE THREAD

**Issue by RusGraf** [redis/RedisDesktopManager#3362]
Crashing if you have multiple connections opened in the same time, at the time when you are browsing through nodes. Pretty consistent. We have a master and slave configuration and its only allow us to connect one at the time.

**Comment by uglide** [comment]
Hello @RusGraf and thank you for the feedback!
Which version of RDM and platform do you use?

**Comment by abienkowski** [comment]
Same issues here v0.7.6

**Comment by uglide** [comment]
@RusGraf @abienkowski Please try 0.7.9.X builds

**Comment by RusGraf** [comment]
Hello,
Sorry for such a late response. Yes i'm using the 0.7.6 version, i will
give 0.7.9 a shot and will let you know if i see this issue again.

Thanks a lot,
Ruslan Guryanov

On Thu, Jun 11, 2015 at 5:32 AM, Igor Malinovskiy notifications@github.com
wrote:

> @RusGraf https://github.com/RusGraf @abienkowski
> https://github.com/abienkowski Please try 0.7.9.X builds
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uglide/RedisDesktopManager/issues/3362#issuecomment-111063476
> .

## 

Thank you,
Ruslan Guryanov

**Comment by uglide** [comment]
Cannot reproduce on latest 0.7.9.X build on Ubuntu

**Comment by abienkowski** [comment]
I find many ways the application crashing.

Here is another one
1) Add a filter key
2) remove filter key

or

1) add a filter key
2) reload  (workaround for the above issue)
3) add a filter key
4) repeat 4-5 times.

**Comment by uglide** [comment]
Adrian,

Do you use latest beta build 0.7.9.X or old 0.7.6?

2015-07-17 13:47 GMT+03:00 Adrian Bienkowski notifications@github.com:

**Comment by uglide** [comment]
@RusGraf, @abienkowski 
Please use the latest beta builds 0.7.9.X. This problem was fixed.

**Comment by abienkowski** [comment]
Just updated to the latest 0.7.9.514 build.

And still crashing. As soon as you add a filter and traverse through the tree, it randomly crashes.

Very unstable!

**Comment by abienkowski** [comment]
created a new issues under #3392
