### ISSUE TITLE
Scores are being written in scientific notation?

### ISSUE THREAD

**Issue by dikkeduif** [redis/RedisDesktopManager#3518]
In previous versions of RDM the scores were displayed in full. Is there any way to toggle this new behavior? It seems the scores are shown in scientific notation now? I didn't update rdm in a while, but I've noticed this in 0.8.1

![screenshot from 2015-10-26 14-01-37](https://cloud.githubusercontent.com/assets/5879625/10728435/6757b08e-7bea-11e5-9050-8423b092f0f3.png)

**Comment by uglide** [comment]
Fixed in 0.8.3

**Comment by donalddw** [comment]
@uglide I'm still having issues with this. It looks like it's trying to format data incorrectly. For example

via redis-cli
cmd: zscore broadcast_guest_users:750473 755808
returns: "100000000060000"

In rdm I get the following (note the 6 is gone)
![screenshot from 2015-11-16 08-18-54](https://cloud.githubusercontent.com/assets/11804208/11175440/df07c122-8c3a-11e5-8777-19f2693379f8.png)

**Comment by uglide** [comment]
@donalddw Please check latest fix from 0.8.0 branch. Thanks!

**Comment by donalddw** [comment]
@uglide yes! looks good! thanks
