### ISSUE TITLE
RDM crashes when large amount of data to load.

### ISSUE THREAD

**Issue by yuxuac** [redis/RedisDesktopManager#3599]
RDM Version: 0.8.3.3850<br>
Environment: (Windows 8.1- 64bit) <br>
Redis Server Version: 3.0.501<br>

Steps to reproduce:
1. Insert more than 6,000,000 items into Redis.(key's length is around 20 characters, value is only a decimal number.)
2. Open db use RDM
3. RDM crashed.(Memory consumption is more than 90% (Total: 8G))

Expected result: RDM display all values, or inform user memory is not enough.

Actual Result: RDM crashed.
##

**Comment by m3talstorm** [comment]
Seeing this as well

**Comment by uglide** [comment]
Starting from 0.8.8 will be able to use up to 4G of RAM it's enough to handle loading of 6M keys without namespaces. Actual fix will be implemented in 0.9.X versions

**Comment by rpresnakov** [comment]
Was this issue fixed in 0.9.9 version? I've just installed it and I'm unable to load the entire keys tree (9.5 million keys) - RDM crashed several times.

RDM version 0.9.9
OS: Windows 10 Enterprise 64 bit
Redis version 5.0 (AWS ElastiCache)

**Comment by uglide** [comment]
Fixed in 2019 branch. In the scenario described by @yuxuac RDM 2019 is able to build a plain tree with ~7Gb of free memory + added basic handling for out of memory exceptions.

**Comment by yegors** [comment]
Issue still occurring. Trying to load a DB with ~10M keys, the app crashes. I have 64GB of RAM, and memory is not exhausted.

**Comment by uglide** [comment]
@yegors Are you using build from 2019 branch?
