### ISSUE TITLE
Windows tabs are all black background via RDP

### ISSUE THREAD

**Issue by dlindbergjhs** [redis/RedisDesktopManager#3626]
RDM Version: 0.8.3<br>
Environment (OS name and version): Windows 7<br>
Redis Server Version: Azure<br>

Steps to reproduce:
1. Launch windows version...
2. observe black background...
3. ...

Expected result: 
Should be able to read the text in the tab on the right.

Actual Result: 
See black background
![redisscreenshot](https://cloud.githubusercontent.com/assets/4650734/16148939/16647ac0-345b-11e6-9b26-7799da3c991f.png)

**Comment by uglide** [comment]
@dlindbergjhs please try latest version https://github.com/uglide/RedisDesktopManager/releases/tag/0.8.4

**Comment by dlindbergjhs** [comment]
Just installed 0.8.4.  I has the same issue.
Thanks -- Dan'l

**Comment by uglide** [comment]
@dlindbergjhs Do you use RDP or running it on VM?

**Comment by dlindbergjhs** [comment]
No.  It's running locally.
We do have one running on a 2012 R2 VM that works properly.
And it looks good on my Mac.

**Comment by uglide** [comment]
@dlindbergjhs Could you describe your PC hardware configuration? Especially I interested in GPU specs

**Comment by dlindbergjhs** [comment]
Sorry, yes.  Today i am RDPd into the Windows machine.
![dan laptop specs display](https://cloud.githubusercontent.com/assets/4650734/16149435/bce76e7c-345e-11e6-8ccd-bb076d88fa6e.png)
![dan laptop specs](https://cloud.githubusercontent.com/assets/4650734/16149438/c012aff8-345e-11e6-9eeb-5aa621408e60.png)

**Comment by uglide** [comment]
@dlindbergjhs ok, thanks for the info

**Comment by dlindbergjhs** [comment]
Just an FYI, it works fine when i'm not RDPd in.  I just verified that.
I also just changed the RDP settings to display highest quality and it's working fine via RDP too.

**Comment by uglide** [comment]
Fixed in 0.8.6

**Comment by 82ndab-Bravo17** [comment]
Im afraid that I still get the black screen when using RDP with the latest version.

Windows 2008 R2, Display adapter shows as Standard VGA adapter

**Comment by uglide** [comment]
@82ndab-Bravo17 your rdp connection should have directx support enabled to be able to view RDM (enable all vosual settings in RDP settings on the client). Also Do you have SP1 installed?

**Comment by 82ndab-Bravo17** [comment]
Thanks for the quick reply.

Yes, we have SP1 installed. Couldn't find many display settings to change in client RDP, just desktop size and color depth, unless I am missing something?

Version 7.6 still works fine, just nothing after that.

**Comment by uglide** [comment]
@82ndab-Bravo17  you should install RemoteFX http://social.technet.microsoft.com/wiki/contents/articles/16652.remotefx-vgpu-setup-and-configuration-guide-for-windows-server-2012.aspx

**Comment by 82ndab-Bravo17** [comment]
Unfortunately that seems to be for a hyperV instance, not a machine over the internet via rdp

**Comment by yangjiebeijing** [comment]
hi  i think  i have the same question  my system is Windows 2008 R2,  it is not possiable for me to upgrade to  2012 ，i want to know which version i can use except 7.6.15?  the latter version?

**Comment by uglide** [comment]
@yangjiebeijing 

Select following RDP settings:
![image](https://cloud.githubusercontent.com/assets/1655867/17548914/a5f2eed6-5ef6-11e6-8883-e979921e25e1.png)

And double check that you have latest GPU driver installed on the server. At least it works for me when I connect to Windows 7 via RDP

**Comment by yangjiebeijing** [comment]
its not worked, my server  is windows 2008 R2

**Comment by yangjiebeijing** [comment]
ithink i must install RemoteFX and the color must be set 32 not 16（Dispaly tab）
one of my servers was worked， thanks
