### ISSUE TITLE
Failed to clone '3rdparty/qgamp' a second time, aborting

### ISSUE THREAD

**Issue by locan** [redis/RedisDesktopManager#3821]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:
git clone --recursive https://github.com/uglide/RedisDesktopManager.git

Expected result: 

Actual Result: 
Cloning into 'RedisDesktopManager'...
remote: Counting objects: 15079, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 15079 (delta 0), reused 0 (delta 0), pack-reused 15076
Receiving objects: 100% (15079/15079), 70.57 MiB | 328.00 KiB/s, done.
Resolving deltas: 100% (8861/8861), done.
Submodule '3rdparty/crashreporter' (https://github.com/RedisDesktop/CrashReporter.git) registered for path '3rdparty/crashreporter'
Submodule '3rdparty/easyloggingpp' (https://github.com/easylogging/easyloggingpp.git) registered for path '3rdparty/easyloggingpp'
Submodule '3rdparty/gbreakpad' (https://chromium.googlesource.com/breakpad/breakpad) registered for path '3rdparty/gbreakpad'
Submodule '3rdparty/qgamp' (https://github.com/uglide/qgamp.git) registered for path '3rdparty/qgamp'
Submodule '3rdparty/qredisclient' (https://github.com/uglide/qredisclient.git) registered for path '3rdparty/qredisclient'
Submodule 'src/qml/3rdparty/php-unserialize-js' (https://github.com/uglide/php-unserialize-js.git) registered for path 'src/qml/3rdparty/php-unserialize-js'
Cloning into '/Users/*/codes/RedisDesktopManager/3rdparty/crashreporter'...
Cloning into '/Users/*/codes/RedisDesktopManager/3rdparty/easyloggingpp'...
Cloning into '/Users/*/codes/RedisDesktopManager/3rdparty/gbreakpad'...
Cloning into '/Users/*/codes/RedisDesktopManager/3rdparty/qgamp'...
remote: Repository not found.
fatal: repository 'https://github.com/uglide/qgamp.git/' not found
fatal: clone of 'https://github.com/uglide/qgamp.git' into submodule path '/Users/*/codes/RedisDesktopManager/3rdparty/qgamp' failed
Failed to clone '3rdparty/qgamp'. Retry scheduled
Cloning into '/Users/*/codes/RedisDesktopManager/3rdparty/qredisclient'...
Cloning into '/Users/*/codes/RedisDesktopManager/src/qml/3rdparty/php-unserialize-js'...
remote: Repository not found.
fatal: repository 'https://github.com/uglide/php-unserialize-js.git/' not found
fatal: clone of 'https://github.com/uglide/php-unserialize-js.git' into submodule path '/Users/*/codes/RedisDesktopManager/src/qml/3rdparty/php-unserialize-js' failed
Failed to clone 'src/qml/3rdparty/php-unserialize-js'. Retry scheduled
Cloning into '/Users/*/codes/RedisDesktopManager/3rdparty/qgamp'...

**Comment by uglide** [comment]
Legacy repos were removed. Fix will be on friday this week in this PR https://github.com/uglide/RedisDesktopManager/pull/3781

**Comment by locan** [comment]
THX

**Comment by uglide** [comment]
Fixed in 44c62a0, you can clone alpha4 branch

**Comment by ghost** [comment]
The issue is still present when trying to download version 0.8.8 (which works for older versions of redis)

**Comment by donalddewulf** [comment]
You might want to change the documentation at http://docs.redisdesktop.com/en/latest/install/#build-from-source and remove the branch number when cloning the repo so it clones into 0.9 by default.

It would be nice if you could provide a complete tar file with all the 3rd party modules included, so the build process can still be completed for 0.8.8. The other option would be to install the windows version from https://github.com/uglide/RedisDesktopManager/releases/tag/0.8.8 with wine...
