### ISSUE TITLE
Scrollbar cannot be selected in 0.9.0

### ISSUE THREAD

**Issue by Jerry-Shaw** [redis/RedisDesktopManager#3968]
RDM Version: 0.9.0<br>
Environment (OS name and version): Win10 x64<br>
Redis Server Version: 4.0.2<br>

Steps to reproduce:

1. Connect to Redis server.

2. Open a DB with many keys inside. Long list of keys.

3. Cannot click on scrollbar and drag to scroll to somewhere in the key list. Only mouse wheel can be using to scroll slowly. What makes it very hard to quickly browse the keys if there are many keys.

Expected result: Click on scrollbar and drag down or up quickly to where we need.

Actual Result: Only mouse wheel works.

**Comment by uglide** [comment]
@Jerry-Shaw Could you specify screen resolution? I'm asking because scrollbar is partially hidden only on 4k monitor, but still usable. Most likely your issue is related to #3876

**Comment by r4nyc** [comment]
When I put the mouse cursor over the scroll bar it changes to the splitter control. Instead of being able select and scroll, it ends up adjusting the split. The splitter cursor is showing up for quite a wide area.

I'm on the same version of windows and rdm as the original poster. The mouse cursor isn't showing up when I PrtScn, but I drew in an arrow to indicate the area where the split cursor is appearing
![no_scroll](https://user-images.githubusercontent.com/12448959/36050946-6fbc004e-0db6-11e8-98d4-ed338f99ca39.png)

**Comment by Jerry-Shaw** [comment]
@uglide  My screen resolution is 1920 x 1080, but all size of text, app, items are set to 125% as recommended in Win 10.
Yep, very likely to https://github.com/uglide/RedisDesktopManager/issues/3876

**Comment by Jerry-Shaw** [comment]
@r4nyc Yep, we are the same. Have you set the size to 125%? Or just original size?

**Comment by uglide** [comment]
@Jerry-Shaw 

 Could you try this build https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.732/artifacts

**Comment by uglide** [comment]
Scrollbar issue on 4k monitor on Windows is fixed in 0.9.0-3

**Comment by Jerry-Shaw** [comment]
@uglide  , sorry for the late test, I was in festival, and just back today. 
No, it is not fixed yet both in 0.9.0.732 and 0.9.0.738, just tested.

**Comment by uglide** [comment]
Could you provide some screenshots?

вс, 25 февр. 2018 г., 8:57 Jerry <notifications@github.com>:

**Comment by Jerry-Shaw** [comment]
@uglide , here are the screenshots of  0.9.0.732 and 0.9.0.738. They look the same. I took a photo of 0.9.0.738 bellow, which shows the mouse icon on scrollbar.

![0 9 0 732](https://user-images.githubusercontent.com/13212198/36642205-f7a4c398-1a76-11e8-8366-aed4cf5707db.png)
![0 9 0 738](https://user-images.githubusercontent.com/13212198/36642212-13a19fc6-1a77-11e8-8945-b5065ce02f33.png)
![photo of scroll bar](https://user-images.githubusercontent.com/13212198/36642219-32486d06-1a77-11e8-9ef4-8be4a4f9cb59.jpg)

**Comment by Jerry-Shaw** [comment]
@uglide Seems like the problem still exists under 4K screen with 250% scale.
BTW, could we make the width of left sidebar which contains connections and keys changeable? It becomes too wide and has the minimal width limitation, which makes the right part sort of narrow to show under high DPI with higher scale. 

Here are screenshots.

![rm tq5fud wa 7i9koj2m59](https://user-images.githubusercontent.com/13212198/49559093-6e66ea00-f948-11e8-9cbd-39bda1521744.png)
![img_20181206_111235r](https://user-images.githubusercontent.com/13212198/49559096-7161da80-f948-11e8-8c0c-b28a85756241.jpg)
