### ISSUE TITLE
SSH connections cause crash

### ISSUE THREAD

**Issue by daydaygo** [redis/RedisDesktopManager#4000]
RDM Version: 0.9<br>
Environment (OS name and version): win10<br>
Redis Server Version: 3.6 / 4.0<br>

Steps to reproduce:

1. install RDM in win10

2. add connection by ssh with pem privatekey

3. add connection by ssh with password

Expected result: add connection 

Actual Result: RDM crashed

**Comment by uglide** [comment]
@daydaygo It's not clear what kind of credentials do you use. Is it ssh pem key with password?

**Comment by daydaygo** [comment]
i have try both pem key or password, both way will end with crashing

**Comment by cloudbluedigital** [comment]
same happens to me, it works until I either try to connect to existing redis connection or test new redis connection.

**Comment by cloudbluedigital** [comment]
Any update on this? Do you need some more information?

**Comment by uglide** [comment]
Fixed. Will be available tomorrow in 0.9.0-5

**Comment by cloudbluedigital** [comment]
unfortunately @uglide the new update doesn't fix the issue. What could be causing this? is the any log etc that can be checked/posted?

**Comment by uglide** [comment]
@cloudbluedigital Do you use Windows build redis-desktop-manager-0.9.0.760.exe ?

**Comment by cloudbluedigital** [comment]
yes @uglide I have updated it before putting a comment

**Comment by robeastwood** [comment]
I am still having this issue also. Just upgraded to version 0.9.0.760 to try and fix it but no joy.
I'm running on Windows 7.

 - Adding a connection using SSH tunnel with key, & clicking Test Connection = Crash
 - Adding a connection using SSH tunnel with key & saving = connection saved.
Try to connect to it = Crash.

Any ideas of things to try?

**Comment by cloudbluedigital** [comment]
When is this going to be released @uglide ?

**Comment by uglide** [comment]
It's not tagged yet but it's available in latest builds https://ci.appveyor.com/project/uglide/redisdesktopmanager/branch/0.9/artifacts
