### ISSUE TITLE
Windows - Crash when trying to connect

### ISSUE THREAD

**Issue by cloudbluedigital** [redis/RedisDesktopManager#4033]
RDM Version: latest
Environment (OS name and version): Windows 10 1709
Redis Server Version: latest

Steps to reproduce:

1. Install RDM

2. Setup connection

3. Test Connection

Expected result: Success/Error message

Actual Result: App crashes, tried running through CMD, nothing helped. My drivers are up to date it's running on Intel UHD graphics 6200

**Comment by cherbert** [comment]
Clicking on Settings and changing Language from system to en_US fixed it for me. Although testing a connection still crashes the client. If I just click OK it creates a new connection profile and connects ok.

**Comment by cherbert** [comment]
Clicking on Settings and changing Language from system to en_US fixed it for me. Although testing a connection still crashes the client. If I just click OK it creates a new connection profile and connects ok.

**Comment by derekgreer** [comment]
I'm having the same issue.  Clicking on Settings crashes for me just like trying to open the connection dialog.  Afterwards when I try to restart, it immediately crashes.

**Comment by uglide** [comment]
Hello guys
Please try to use this build
https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.747/artifacts

**Comment by uglide** [comment]
Should be fixed in 0.9.0-4

**Comment by derekgreer** [comment]
That build worked for me.  Thanks for the quick turn around!

**Comment by cloudbluedigital** [comment]
Unfortunately I still get the issue :(


![image](https://user-images.githubusercontent.com/22678404/36905554-943a9590-1e2b-11e8-951c-ae86d24f18d4.png)

**Comment by uglide** [comment]
@cloudbluedigital ssh crash on windows is not fixed yet #4000

**Comment by cloudbluedigital** [comment]
ahh okay @uglide, thanks I will be awaiting for a next update ;)
