### ISSUE TITLE
Value of key not rendering

### ISSUE THREAD

**Issue by rfigueroa2014** [redis/RedisDesktopManager#4794]
**Describe the bug**
The key values are not being displayed

**To Reproduce**
Cache a key and then get the keys and look at value

**Expected behavior**
see key vlaue

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
Please provide more details:

- RDM version
- OS & version
- Sample of value

**Comment by rfigueroa2014** [comment]
RDM Version: 2020.0.193
OS: Windows 10 Version: 18362.10022

Value:
{“success”:true, “message”:””, “outage”:”test” }

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>

**Comment by rfigueroa2014** [comment]
Looks like it’s a font-color issue.  The content is there but the background and forground colors are both white
[cid:image002.png@01D6244F.7AAA3640]

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>


From: Figueroa, Ruben
Sent: Thursday, May 7, 2020 8:56 AM
To: uglide/RedisDesktopManager <reply@reply.github.com>; uglide/RedisDesktopManager <RedisDesktopManager@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [External Email] Re: [uglide/RedisDesktopManager] Value of key not rendering (#4794)

RDM Version: 2020.0.193
OS: Windows 10 Version: 18362.10022

Value:
{“success”:true, “message”:””, “outage”:”test” }

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>

**Comment by uglide** [comment]
Please attach screenshot via Github webpage. It's not viewable.

**Comment by rfigueroa2014** [comment]
[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>


From: Figueroa, Ruben
Sent: Thursday, May 7, 2020 9:11 AM
To: 'uglide/RedisDesktopManager' <reply@reply.github.com>; 'uglide/RedisDesktopManager' <RedisDesktopManager@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [External Email] Re: [uglide/RedisDesktopManager] Value of key not rendering (#4794)

Looks like it’s a font-color issue.  The content is there but the background and forground colors are both white
[cid:image005.png@01D62463.7F561B00]

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>


From: Figueroa, Ruben
Sent: Thursday, May 7, 2020 8:56 AM
To: uglide/RedisDesktopManager <reply@reply.github.com<mailto:reply@reply.github.com>>; uglide/RedisDesktopManager <RedisDesktopManager@noreply.github.com<mailto:RedisDesktopManager@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [External Email] Re: [uglide/RedisDesktopManager] Value of key not rendering (#4794)

RDM Version: 2020.0.193
OS: Windows 10 Version: 18362.10022

Value:
{“success”:true, “message”:””, “outage”:”test” }

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>

**Comment by Leon99** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/6840381/82619021-15604400-9c18-11ea-89a2-bec11bc91303.png)
The actual value is there and can be acquired with copy & paste, it looks like the white font is used for all but "Plain Text" formats.
![image](https://user-images.githubusercontent.com/6840381/82619083-4c365a00-9c18-11ea-80e2-924a63c6a5a6.png)

**Comment by uglide** [comment]
@Leon99 could you please provide some sample value?

**Comment by Leon99** [comment]
`"2020-05-22T09:33:35.0318287Z"`

**Comment by uglide** [comment]
@Leon99  thanks

**Comment by uglide** [comment]
@Leon99 is your value serialized somehow? I cannot reproduce the issue with the plain text `"2020-05-22T09:33:35.0318287Z"`

**Comment by shannonlharris** [comment]
I'm experiencing the same issue.  Values are there as if a select, copy, paste to a text editor is used, I  can see the values.  As noted above, it's as if white font color is used

**Comment by Leon99** [comment]
It's serialized using https://www.nuget.org/packages/MessagePack/

Will the raw value help?
As hex: `\xD7\xFF>\x8AG@^\xCB\x19\xA4`
As hex table: `00000000: d7ff 3e8a 4740 5ecb 19a4`

**Comment by uglide** [comment]
@rfigueroa2014 @Leon99 Please try 2020.1-beta1 builds from https://redisdesktop.com/subscriptions (Preview Builds Tab)

**Comment by rfigueroa2014** [comment]
Cannot login from application to subscription now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by uglide** [comment]
@rfigueroa2014 sorry for the inconvenience.  It should work now.

**Comment by rfigueroa2014** [comment]
Still not visible (text color and background color are identical)
[cid:image001.png@01D63A57.12EE2110]

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>

**Comment by uglide** [comment]
@shannonlharris @rfigueroa2014 Could you please provide more detailed steps to reproduce with sample data?

**Comment by rfigueroa2014** [comment]
Connect to Redis server
Load DB
And click on a key

[Quadient]
RUBEN FIGUEROA
IT Manager - Corporate Apps
r.figueroa@quadient.com<mailto:r.figueroa@quadient.com>
+01 203 301 3739
478 Wheelers Farm Rd
Milford CT 06460 - USA
www.quadient.com<https://www.quadient.com/>
Learn more about Quadient<https://www.quadient.com/connections>
