### ISSUE TITLE
Can't clone database from other server

### ISSUE THREAD

**Issue by polearnik** [redis/RedisDesktopManager#4815]
**Describe the bug**

**To Reproduce**
Install from snap 
1. Go to 'database on other server'
2. Click on 'copy keys from this database to another'
3. In window select localhost and any database 
4. Press 'copy keys' button
5. Nothing happens

Logs:
![Снимок экрана от 2020-05-29 08-46-15](https://user-images.githubusercontent.com/17157321/83225784-09243b80-a170-11ea-9b6d-f977e5a6030f.png)

**Environment (please complete the following information):**
 - OS & version: Linux Mint 19.3 Cinnamon edition
 - Redis-Server version [e.g. 5.0.1]

**Additional context**
Its broken from previous stable version. Exporting connections , removing and reinstalling with snap not fix issue

**Comment by uglide** [comment]
Fixed in 2020.0+2e72ed21. Please refresh snap

**Comment by polearnik** [comment]
the bug is still persist.
 I using version 2020.4+6a635b62. 
Linux mint is updated to 20 version. 
Its stopped on this screen 
server is very close to me 

![2020-10-12_14-08-59](https://user-images.githubusercontent.com/17157321/95740055-616d5d00-0c7b-11eb-9b96-bf161c4ce95a.png)

ssh address is an ip address
![2020-10-12_14-11-32](https://user-images.githubusercontent.com/17157321/95740282-bc06b900-0c7b-11eb-9618-307ea4e941f1.png)

**Comment by polearnik** [comment]
the problem still persist. I cant clone keys from one server to another. It stuck on getting list of affected keys

**Comment by uglide** [comment]
@polearnik please provide exact version numbers of redis-servers on both sides
Does it copy at least something to the target redis-server or not?

**Comment by polearnik** [comment]
No/ it dont copy anything to target server. 

On my home appt i have setuped 2 server connection via ssh tunnel . If I try to copy keys from first server to second it stuck

on both servers  same versions
# Server
redis_version:6.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d463d609620685c0
redis_mode:standalone
os:Linux 5.4.0-96-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:9.3.0
process_id:1374
run_id:26cfa78ee62f121b8e7c71afc66420a3682a83e4
tcp_port:6379
uptime_in_seconds:1106712
uptime_in_days:12
hz:10
configured_hz:10
lru_clock:5605372
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

**Comment by uglide** [comment]
Ok, thanks for the details. I will try to reproduce the issue
