### ISSUE TITLE
RDM window does not resize on Windows 10 laptop

### ISSUE THREAD

**Issue by mia-at-speechmorphing** [redis/RedisDesktopManager#4845]
I just downloaded and installed RedisDesktopManager, and it is extremely useful (I used the free version in the past) but now application starts too big - and in addition I cannot resize the application window, and it is too big - so much so that I cannot view the end of the keys list!
It also covers too mych "real estate" on my screen.

attached screenshots of how the application starts (not as full screen) 
![too-big-startup](https://user-images.githubusercontent.com/17604334/87099350-55967880-c1fe-11ea-9856-d0daac6981f8.PNG)

and how it looks when I cannot view the bottom element. 
![too-big1](https://user-images.githubusercontent.com/17604334/87099326-41eb1200-c1fe-11ea-8fb3-5d1cbfd5f410.PNG)

**Expected behavior**
I would like to be able to resize the window and have scroll bars for top-bottom and left-right scrolling/navigation.

**Environment**
Microsoft Windows 10 Home
version 10.0.18362 Build 18362 

thank you
Mia

**Comment by mrnom** [comment]
@mia-at-speechmorphing 
Hi Mia, please provide your screen resolution and display scale factor.

**Comment by mia-at-speechmorphing** [comment]
Thank you for the reply

screen resolution is (recommended) 3840x2160
display is landscape, scale factor is (recommended) 250%

thanks
Mia

**Comment by uglide** [comment]
@mia-at-speechmorphing Could you please try 2020.2-beta1 (2020.2.222) build from our website (you can just sign up for free trial)?

**Comment by mia-at-speechmorphing** [comment]
Sorry, I am obviously doing somethingn wrong... I cannot get version 2020.2.222 - I signed up for free trial but I cannot download etc., I also don't see the version on github. help?

**Comment by uglide** [comment]
@mia-at-speechmorphing Please click on "Preview builds" tab and you will see 2020.2-beta1 download links:
![image](https://user-images.githubusercontent.com/1655867/89159181-d5063600-d577-11ea-84a6-105b071f1101.png)

**Comment by mia-at-speechmorphing** [comment]
sorry, uglide
I subscribed, logged in, clicked on the windows link and got message:

Nice try :) Please buy subscription first or send pull request to RedisDesktopManager to have access to all RDM releases.

thanks

**Comment by uglide** [comment]
@mia-at-speechmorphing Sorry about that. This issue was resolved. Please try download again.

**Comment by mia-at-speechmorphing** [comment]
Thank you, the program is now well within the bounds of the screen.
I still cannot make it samller, but this is understandable.
hope the new  release be available soon.

**Comment by uglide** [comment]
@mia-at-speechmorphing thanks for the feedback!
