### ISSUE TITLE
very slow key display

### ISSUE THREAD

**Issue by mia-at-speechmorphing** [redis/RedisDesktopManager#4924]
I am running RDM version 2020.4.35 on a Dell laptop 
intel i7-550U 2.40GHz, 12GB ram, windows 10 home 64 bit  version 2004

I am running Redis-3.0.5 locally on my windows machine (there is no more advanced Redis for windows, I verified with Redis engineer).
 
my key display time is VERY slow, I mean, 20+ seconds for a simple string value for a key.
moreover, just one click on the key would not open the value - I need to double click it, at which time the RDM application sometimes goes inactive (not just the "churn" icon) before value is displayed.
even when I try to display a value that was displayed a moment earlier, it still takes all this time.

attached is a screenshot for example, of key structure - and key value 
- but this happend for any key, and also on remote Redis (newest Redis version on a Linux server) as well as on local Redis.

previous version(s) of RDM were as quick as lightening, on refresh time. I am not sure what happened.

Thank you
Mia

![rdm-slow](https://user-images.githubusercontent.com/17604334/96321988-30b75b80-0fcc-11eb-86ae-a16027bb1436.jpg)

**Comment by uglide** [comment]
Hello @mia-at-speechmorphing 
Do you use `127.0.0.1 `as Redis host in settings or `localhost`?

**Comment by mia-at-speechmorphing** [comment]
Hello
I use 127.0.0.1

also it happens for other ip addresses I use as plain IP (not DNS)
thank you.

**Comment by uglide** [comment]
@mia-at-speechmorphing  Please collect more debug information with DebugView https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
1. Download & run DebugView
2. Run RDM & Reproduce the issue
3. Make a screenshot of the Log drawer in RDM (Click on "Log" button in the top right corner)
4. Save log in Debug View (Ctrl + S) to file and send it to igor@rdm.dev

**Comment by mia-at-speechmorphing** [comment]
emailed...

**Comment by uglide** [comment]
@mia-at-speechmorphing received, thanks!

Looks like you have faced 2 or more separate issues. 
1. Old redis-server port is buggy and need to be restarted frequently to operate fast. I recommend to install Ubuntu 18/20 in WSL2 and install latest redis-server inside Ubuntu WSL2 VM. It will be available from Windows side as local redis-server.
2. Issue with cluster redirects was fixed and released in 2020.5. Please try to update to 2020.5.39 in Microsoft Store and check remote server connections.

**Comment by mia-at-speechmorphing** [comment]
Thaks for the advise, here is what I did:
downloaded newest version (I have RDM 2020.5.39)
I restarted my Redis server (it is on windows, so not new, but restarting should hopefully help with redis server port)
I restarted RDM

I still experience similar behavior. 
I will repeat debug view etc. and email you the results in a short while.
thank yoou.

**Comment by mia-at-speechmorphing** [comment]
sorry, as I said, delay in timing is similar with new version 2020.5.39.

With RDM 2020.5.39 I experience a new, worse symptom: value **not displayed** for key which is not a JSON, and "view-as" is set to JSON
both localhost (Windows) and remote (Linux) Redis servers.
emailing you screenshots and logs.
thanks

**Comment by uglide** [comment]
@mia-at-speechmorphing regression with JSON formattter was fixed 2020.5.41 but original issue I haven't reproduced yet.

**Comment by mia-at-speechmorphing** [comment]
2020.5.41  indeed fixed theJSON issue.
I still experience very long delay when opening keys.
please see email respoonse also. thanks!

**Comment by uglide** [comment]
Fixed in 2020.6
